import Groq from 'groq-sdk'

const GROQ_API_KEY = import.meta.env.VITE_GROQ_API_KEY || 'your-groq-api-key-here'

const groq = new Groq({
  apiKey: GROQ_API_KEY,
  dangerouslyAllowBrowser: true
})

export const sendMessageToGroq = async (messages) => {
  // For GitHub Pages deployment, use intelligent fallback responses
  // In a production environment with proper backend, this would use the actual Groq API
  
  const userMessage = messages[messages.length - 1]?.content?.toLowerCase() || ''
  
  // Advanced pattern matching for educational responses
  const responses = {
    // Solar PV responses
    'solar pv': '🌞 **Solar PV (Photovoltaic) Systems** convert sunlight directly into electricity using semiconductor materials like silicon. When photons hit the solar cells, they knock electrons loose, creating an electric current. Modern PV systems can achieve 20-22% efficiency and last 25-30 years. Key components include solar panels, inverters, mounting systems, and monitoring equipment. PV systems can be grid-tied (connected to the utility grid) or off-grid with battery storage.',
    
    'solar panel': '⚡ **Solar panels** are made up of many photovoltaic cells, typically silicon-based, that convert sunlight into DC electricity. Each cell generates about 0.5-0.6 volts. Panels are rated by their peak power output (measured in watts) under standard test conditions. They\'re connected in series to create strings, and multiple strings are connected in parallel to achieve the desired voltage and current for your system.',
    
    'photovoltaic': '🔬 **Photovoltaic effect** was discovered by Alexandre Edmond Becquerel in 1839. It occurs when certain materials absorb photons and release electrons, creating electricity. Silicon PV cells use a p-n junction - when light hits the cell, electrons move from the n-type to p-type material, creating voltage. This is different from solar thermal, which uses heat rather than the photovoltaic effect.',

    // Wind Power responses
    'wind power': '💨 **Wind power** harnesses kinetic energy from moving air using turbines with aerodynamic blades. Modern wind turbines are typically 80-120 meters tall with three-blade designs optimized for efficiency. The wind turns the rotor, which connects to a gearbox that increases rotation speed for the generator. Wind energy is one of the fastest-growing renewable sources, with capacity factors of 35-45% in good locations.',
    
    'wind turbine': '🌪️ **Wind turbines** consist of several key components: rotor blades (designed with aerodynamic lift principles), nacelle (housing the gearbox and generator), tower (providing height to access stronger winds), and foundation. The cut-in speed is typically 3-4 m/s, rated speed around 12-15 m/s, and cut-out speed at 25 m/s for safety. Pitch control adjusts blade angles to optimize performance.',
    
    'wind energy': '🌬️ **Wind energy** is generated by uneven heating of Earth\'s surface by the sun, creating pressure differences and air movement. Wind power density increases with the cube of wind speed, so doubling wind speed gives 8x more power! Offshore wind typically has higher and more consistent speeds than onshore. Wind farms can be designed to minimize wake effects between turbines.',

    // Hydropower responses
    'hydropower': '💧 **Hydropower** generates electricity using flowing or falling water to turn turbines connected to generators. It\'s the world\'s oldest and most widely used renewable energy source. Types include run-of-river (no dam), reservoir-based (large dams), and pumped storage (energy storage). Head (height) and flow rate determine power output: P = ρ × g × Q × H × η (where ρ=water density, Q=flow rate, H=head height, η=efficiency).',
    
    'hydroelectric': '⚡ **Hydroelectric power** plants convert the potential energy of water at height into kinetic energy, then into electrical energy. Francis turbines are most common for medium head applications, Pelton wheels for high head, and Kaplan turbines for low head/high flow. Modern plants can achieve 90%+ efficiency and provide grid stability services like frequency regulation.',
    
    'water turbine': '🌊 **Water turbines** come in two main types: impulse (like Pelton wheels) where water jets hit bucket-shaped blades, and reaction turbines (like Francis and Kaplan) where water fills the runner completely. Selection depends on head and flow characteristics. Turbine efficiency is highest at design conditions but modern designs maintain good efficiency across varying flows.',

    // Geothermal responses  
    'geothermal': '🌋 **Geothermal energy** taps into Earth\'s internal heat, originating from the planet\'s formation and radioactive decay. Temperature increases ~25°C per kilometer of depth. Geothermal systems include dry steam, flash steam, and binary cycle power plants. Ground-source heat pumps can extract heat from shallow ground (6-10°C) for building heating/cooling, achieving coefficients of performance (COP) of 3-5.',
    
    'heat pump': '🏠 **Geothermal heat pumps** use the stable ground temperature as a heat source/sink. They circulate fluid through underground loops (horizontal or vertical) to exchange heat with the earth. In winter, they extract heat from the ground; in summer, they reject heat to the ground. Much more efficient than air-source heat pumps, especially in cold climates.',
    
    'geothermal power': '⚡ **Geothermal power plants** require temperatures above 150°C for electricity generation. Flash steam plants are most common - high-pressure hot water flashes to steam when pressure drops. Binary cycle plants use a secondary working fluid with a lower boiling point, allowing power generation from lower temperature resources (85-175°C).',

    // Solar Thermal responses
    'solar thermal': '🔥 **Solar thermal** systems collect and concentrate sunlight to generate heat for various applications. Unlike PV systems that generate electricity directly, solar thermal captures thermal energy. Applications include domestic water heating, space heating, industrial process heat, and concentrated solar power (CSP) for electricity generation. Collector efficiency depends on temperature difference and solar irradiation.',
    
    'solar collector': '☀️ **Solar collectors** come in several types: flat-plate collectors (most common for water heating), evacuated tube collectors (better for cold climates), and concentrating collectors (for high temperatures). Flat-plate collectors have absorber plates with selective coatings to maximize absorption and minimize heat loss. Glazing reduces convective losses while allowing solar transmission.',
    
    'concentrated solar': '🔍 **Concentrated Solar Power (CSP)** uses mirrors to focus sunlight onto a receiver, generating high-temperature heat (400-1000°C) for steam turbines. Types include parabolic trough, solar power tower, parabolic dish, and linear Fresnel systems. CSP can include thermal energy storage using molten salt, allowing power generation even after sunset.',

    // General renewable energy
    'renewable energy': '🌱 **Renewable energy** comes from sources that naturally replenish: solar, wind, hydropower, geothermal, and biomass. Unlike fossil fuels, renewables don\'t deplete with use and produce minimal greenhouse gas emissions. The learning curve effect has dramatically reduced costs - solar PV costs dropped 90% from 2010-2020. Challenges include intermittency (solved with storage and grid flexibility) and initial capital costs.',
    
    'clean energy': '♻️ **Clean energy** technologies produce little to no pollution during operation. Renewable sources like solar and wind have very low lifecycle carbon emissions compared to fossil fuels. Even accounting for manufacturing and installation, renewables typically pay back their energy investment within 1-4 years and then provide decades of clean energy.',
    
    'energy storage': '🔋 **Energy storage** is crucial for renewable integration. Battery storage (lithium-ion, flow batteries) provides short-term flexibility. Pumped hydro storage uses excess energy to pump water uphill, then generates power when needed. Other options include compressed air, thermal storage, and power-to-gas. Storage helps balance supply-demand and provides grid services.',
    
    // Generic helpful responses
    'efficiency': '📊 **Energy efficiency** in renewable systems varies by technology. Solar PV: 15-22%, wind turbines: 35-45%, hydropower: 80-90%, geothermal plants: 10-15% (but very reliable), solar thermal collectors: 50-80%. Efficiency isn\'t everything - availability, cost, and environmental impact also matter. System design and proper maintenance significantly impact real-world efficiency.',
    
    'cost': '💰 **Renewable energy costs** have plummeted due to technological improvements, economies of scale, and learning effects. Solar PV and onshore wind are now the cheapest sources of electricity in most markets. LCOE (Levelized Cost of Electricity) accounts for all lifetime costs. While upfront costs are higher, operational costs are very low since "fuel" (sun, wind, water) is free.',
    
    'environment': '🌍 **Environmental impact** of renewables is generally much lower than fossil fuels. Solar panels and wind turbines pay back their manufacturing energy within 1-4 years, then provide 20-30+ years of clean energy. Hydropower can impact river ecosystems but modern designs minimize this. Geothermal has minimal land use. End-of-life recycling is improving for all technologies.'
  }

  // Advanced pattern matching
  for (const [keyword, response] of Object.entries(responses)) {
    if (userMessage.includes(keyword)) {
      return response
    }
  }

  // Fallback for unmatched queries
  if (userMessage.includes('how') || userMessage.includes('work') || userMessage.includes('explain')) {
    return '🤖 I\'d be happy to explain renewable energy concepts! I can help with:\n\n• **Solar PV** - Photovoltaic systems that convert light to electricity\n• **Wind Power** - Turbines that harness wind energy\n• **Hydropower** - Water-powered electricity generation\n• **Geothermal** - Earth\'s heat for power and heating\n• **Solar Thermal** - Using sunlight for heating applications\n\nTry asking about any of these technologies specifically!'
  }

  try {
    // Only attempt Groq API call if API key is available and valid
    if (GROQ_API_KEY && GROQ_API_KEY !== 'your-groq-api-key-here' && GROQ_API_KEY.startsWith('gsk_')) {
      const systemMessage = {
        role: 'system',
        content: `You are an AI assistant specializing in renewable energy education. Provide clear, educational explanations suitable for university-level students about solar PV, wind power, hydropower, geothermal, and solar thermal technologies.`
      }

      const chatCompletion = await groq.chat.completions.create({
        messages: [systemMessage, ...messages],
        model: 'llama3-8b-8192',
        temperature: 0.7,
        max_tokens: 1000,
      })

      return chatCompletion.choices[0]?.message?.content || 'I apologize, but I couldn\'t process your request. Please try again.'
    }
  } catch (error) {
    console.error('Groq API Error:', error)
    
    // Fallback responses for common renewable energy questions
    const fallbackResponses = {
      'solar': '🌞 Solar energy harnesses sunlight through photovoltaic (PV) panels or solar thermal collectors. PV panels convert sunlight directly into electricity using semiconductor materials, while solar thermal systems capture heat for water heating or power generation. Solar energy is abundant, clean, and increasingly cost-effective!',
      'wind': '💨 Wind power uses turbines to convert kinetic energy from moving air into electricity. Modern wind turbines can be 80-120 meters tall with three-blade designs optimized for efficiency. Wind energy is one of the fastest-growing renewable sources globally!',
      'hydro': '💧 Hydropower generates electricity using flowing water to turn turbines. It can range from large dams to small run-of-river systems. Hydropower provides consistent, reliable energy and can also offer energy storage through pumped hydro systems.',
      'geothermal': '🌋 Geothermal energy taps into Earth\'s internal heat for electricity generation and direct heating. Heat pumps can extract ground heat for buildings, while geothermal power plants use hot water or steam from deep underground.',
      'thermal': '🔥 Solar thermal systems collect and store heat from sunlight. They\'re commonly used for water heating, space heating, and even electricity generation in concentrated solar power plants. These systems are highly efficient for heating applications.'
    }
    
    const userMessage = messages[messages.length - 1]?.content?.toLowerCase() || ''
    
    for (const [keyword, response] of Object.entries(fallbackResponses)) {
      if (userMessage.includes(keyword)) {
        return response
      }
    }
  }
  
  // Default response if no patterns match
  return '🤖 I\'m here to help you learn about renewable energy! I can explain:\n\n• **Solar PV & Solar Thermal** - Photovoltaic and thermal solar systems\n• **Wind Power** - Wind turbines and energy generation\n• **Hydropower** - Water-based electricity generation\n• **Geothermal** - Earth\'s heat for power and heating\n\nTry asking specific questions about any of these technologies!'
}